version: '3.9'
services:
  spark-master:
    ports:
      - "8080:8080"
    expose:
      - 7077
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'bdacs'
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
    expose:
      - 8081
    depends_on:
      - spark-master